server:
  port: 9093

dubbo:
  application:
    name: dubbo-producer
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://192.168.13.128:2181?backup=192.168.13.129:2181,192.168.13.130:2181
    # 设置注册超时时间, 否则zookeeper not connected
    timeout: 100000